# Generated by Django 4.0.3 on 2022-04-19 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
        ('guide', '0003_alter_guideinfo_lastgdelstseen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideinfo',
            old_name='fields',
            new_name='fds',
        ),
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 8, 27, 28, 317691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guideinfo',
            name='questions_byguidees',
            field=models.ManyToManyField(blank=True, related_name='questions_byguidees', to='entry.question'),
        ),
    ]
