# Generated by Django 4.0.3 on 2022-04-21 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_review'),
        ('guide', '0004_rename_fields_guideinfo_fds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideinfo',
            name='rvws_post',
            field=models.ManyToManyField(blank=True, related_name='reviews_posted_bygd', to='entry.review'),
        ),
        migrations.AddField(
            model_name='guideinfo',
            name='rvws_received',
            field=models.ManyToManyField(blank=True, related_name='reviews_received_bygd', to='entry.review'),
        ),
        migrations.AlterField(
            model_name='guideinfo',
            name='fds',
            field=models.ManyToManyField(blank=True, related_name='expertise_fields', to='entry.fields'),
        ),
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 18, 57, 29, 571020, tzinfo=utc)),
        ),
    ]
