# Generated by Django 4.0.3 on 2022-04-21 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_guideinfo_rvws_post_guideinfo_rvws_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 19, 27, 47, 613825, tzinfo=utc)),
        ),
    ]
