# Generated by Django 4.0.3 on 2022-04-21 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_alter_guideinfo_lastgdelstseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 19, 33, 46, 974611, tzinfo=utc)),
        ),
    ]
