# Generated by Django 4.0.3 on 2022-04-22 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_rename_rvws_post_guideinfo_rvws_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 7, 39, 8, 434748, tzinfo=utc)),
        ),
    ]
