# Generated by Django 4.0.3 on 2022-04-22 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_rating_status'),
        ('guide', '0014_alter_guideinfo_lastgdelstseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideinfo',
            name='ratings_given',
            field=models.ManyToManyField(related_name='guide_rated', to='entry.rating'),
        ),
        migrations.AddField(
            model_name='guideinfo',
            name='ratings_received',
            field=models.ManyToManyField(related_name='guide_received', to='entry.rating'),
        ),
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 23, 50, 15, 369954, tzinfo=utc)),
        ),
    ]
