# Generated by Django 4.0.3 on 2022-04-23 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_rating_status'),
        ('guide', '0015_guideinfo_ratings_given_guideinfo_ratings_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 5, 5, 19, 314805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guideinfo',
            name='ratings_given',
            field=models.ManyToManyField(blank=True, related_name='guide_rated', to='entry.rating'),
        ),
        migrations.AlterField(
            model_name='guideinfo',
            name='ratings_received',
            field=models.ManyToManyField(blank=True, related_name='guide_received', to='entry.rating'),
        ),
    ]
