# Generated by Django 4.0.3 on 2022-06-07 19:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import entry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('nid', models.IntegerField()),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('guidees', models.ManyToManyField(blank=True, related_name='guidees', to=settings.AUTH_USER_MODEL)),
                ('guides', models.ManyToManyField(blank=True, related_name='guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usrinfo',
            fields=[
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('DP', models.ImageField(blank=True, upload_to=entry.models.image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvw', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='gde_gd', max_length=15)),
                ('gd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvw_guides', to=settings.AUTH_USER_MODEL)),
                ('gde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvw_guidees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('status', models.CharField(default='gde_gd', max_length=15)),
                ('time_rated', models.DateTimeField(auto_now=True)),
                ('gd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_guides', to=settings.AUTH_USER_MODEL)),
                ('gde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_guidees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('time_asked', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('fd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.fields')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL)),
                ('guidee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_asked'],
            },
        ),
    ]
