# Generated by Django 4.0.3 on 2022-03-31 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedby', models.CharField(blank=True, max_length=500)),
                ('certificate', models.FileField(blank=True, upload_to=entry.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='fields',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('guidees', models.ManyToManyField(blank=True, related_name='guidees', to=settings.AUTH_USER_MODEL)),
                ('guides', models.ManyToManyField(blank=True, related_name='guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usrinfo',
            fields=[
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating', models.FloatField(default=0.0)),
                ('level', models.IntegerField(default=0)),
                ('certificates', models.ManyToManyField(blank=True, to='entry.certificates')),
                ('fdsexpert', models.ManyToManyField(related_name='expertise_fields', to='entry.fields')),
                ('fdsneeded', models.ManyToManyField(related_name='interested_fields', to='entry.fields')),
            ],
        ),
        migrations.AddField(
            model_name='certificates',
            name='fd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.fields'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
