# Generated by Django 4.0.3 on 2022-04-17 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('guidees', models.ManyToManyField(blank=True, related_name='guidees', to=settings.AUTH_USER_MODEL)),
                ('guides', models.ManyToManyField(blank=True, related_name='guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usrinfo',
            fields=[
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('DP', models.ImageField(blank=True, upload_to=entry.models.image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('time_asked', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('fd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.fields')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL)),
                ('guidee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_asked'],
            },
        ),
    ]
