# Generated by Django 4.0.3 on 2022-06-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fields',
            old_name='nid',
            new_name='no',
        ),
    ]
