# Generated by Django 4.0.3 on 2022-04-21 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvw', models.TextField()),
                ('time_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('gd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvw_guides', to=settings.AUTH_USER_MODEL)),
                ('gde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvw_guidees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
