# Generated by Django 4.0.3 on 2022-04-03 05:34

from django.db import migrations, models
import entry.models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrinfo',
            name='DP',
            field=models.ImageField(blank=True, upload_to=entry.models.image_path),
        ),
    ]
