# Generated by Django 4.0.3 on 2022-04-04 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0002_usrinfo_dp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrinfo',
            old_name='rating',
            new_name='guide_rating',
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='guidee_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('time_asked', models.DateTimeField(auto_now=True)),
                ('fd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.fields')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL)),
                ('guidee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='questions_asked',
            field=models.ManyToManyField(related_name='questions_asked', to='entry.question'),
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='questions_byguidees',
            field=models.ManyToManyField(related_name='questions_byguidees', to='entry.question'),
        ),
    ]
