# Generated by Django 4.0.3 on 2022-04-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_rename_rating_usrinfo_guide_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrinfo',
            name='guide_connectmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='guidee_availablemode',
            field=models.IntegerField(default=0),
        ),
    ]
