# Generated by Django 4.0.3 on 2022-04-22 07:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0003_review_status_alter_review_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(default='gde_gd', max_length=15),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('time_rated', models.DateTimeField(auto_now=True)),
                ('gd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_guides', to=settings.AUTH_USER_MODEL)),
                ('gde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_guidees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
