# Generated by Django 4.0.3 on 2022-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_usrinfo_guide_connectmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(),
        ),
    ]
