# Generated by Django 4.0.3 on 2022-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_question_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='seen',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
