# Generated by Django 4.0.3 on 2022-04-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_remove_question_seen_question_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-time_asked']},
        ),
    ]
