# Generated by Django 4.0.3 on 2022-04-27 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_remove_question_seen_question_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-time_asked']},
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 9, 30, 11, 201215, tzinfo=utc)),
        ),
    ]
