# Generated by Django 4.0.3 on 2022-04-05 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrinfo',
            name='guide_lastgdlstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 19, 57, 56, 167139)),
        ),
    ]
