# Generated by Django 4.0.3 on 2022-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_usrinfo_guide_lastgdlstseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdlstseen',
            field=models.DateTimeField(),
        ),
    ]
