# Generated by Django 4.0.3 on 2022-04-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_alter_usrinfo_guide_lastgdlstseen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrinfo',
            old_name='guide_lastgdlstseen',
            new_name='guide_lastgdelstseen',
        ),
    ]
