# Generated by Django 4.0.3 on 2022-04-05 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_rename_guide_lastgdlstseen_usrinfo_guide_lastgdelstseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 17, 38, 8, 553756, tzinfo=utc)),
        ),
    ]
