# Generated by Django 4.0.3 on 2022-04-09 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_alter_usrinfo_guide_lastgdelstseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 16, 23, 31, 505554, tzinfo=utc)),
        ),
    ]
