# Generated by Django 4.0.3 on 2022-04-10 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_alter_usrinfo_guide_lastgdelstseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 6, 11, 54, 265076, tzinfo=utc)),
        ),
    ]
