# Generated by Django 4.0.3 on 2022-04-11 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_alter_usrinfo_guide_lastgdelstseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 7, 21, 4, 599686, tzinfo=utc)),
        ),
    ]
