# Generated by Django 4.0.3 on 2022-04-11 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_status'),
        ('entry', '0019_alter_usrinfo_guide_lastgdelstseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usrinfo',
            name='rooms',
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='guide_rooms',
            field=models.ManyToManyField(blank=True, related_name='guide_rooms', to='chat.room'),
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='guidee_rooms',
            field=models.ManyToManyField(blank=True, related_name='guidee_rooms', to='chat.room'),
        ),
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 7, 53, 54, 269666, tzinfo=utc)),
        ),
    ]
