# Generated by Django 4.0.3 on 2022-04-11 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_remove_usrinfo_rooms_usrinfo_guide_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 17, 38, 19, 130418, tzinfo=utc)),
        ),
    ]
