# Generated by Django 4.0.3 on 2022-06-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0001_initial'),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guideeinfo',
            fields=[
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating', models.FloatField(default=0.0)),
                ('guidee_availablemode', models.IntegerField(default=0)),
                ('fds', models.ManyToManyField(related_name='interested_fields', to='entry.fields')),
                ('guidee_rooms', models.ManyToManyField(blank=True, related_name='guidee_rooms', to='chat.room')),
                ('questions_asked', models.ManyToManyField(blank=True, related_name='questions_asked', to='entry.question')),
                ('ratings_given', models.ManyToManyField(blank=True, related_name='guidee_rated', to='entry.rating')),
                ('ratings_received', models.ManyToManyField(blank=True, related_name='guidee_received', to='entry.rating')),
                ('rvws_posted', models.ManyToManyField(blank=True, related_name='reviews_posted_bygde', to='entry.review')),
                ('rvws_received', models.ManyToManyField(blank=True, related_name='reviews_received_bygde', to='entry.review')),
            ],
        ),
    ]
