# Generated by Django 4.0.3 on 2022-04-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
        ('guidee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideeinfo',
            name='questions_asked',
            field=models.ManyToManyField(blank=True, related_name='questions_asked', to='entry.question'),
        ),
    ]
