# Generated by Django 4.0.3 on 2022-04-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_review'),
        ('guidee', '0002_alter_guideeinfo_questions_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideeinfo',
            name='rvws_post',
            field=models.ManyToManyField(blank=True, related_name='reviews_posted_bygde', to='entry.review'),
        ),
        migrations.AddField(
            model_name='guideeinfo',
            name='rvws_received',
            field=models.ManyToManyField(blank=True, related_name='reviews_received_bygde', to='entry.review'),
        ),
    ]
