# Generated by Django 4.0.3 on 2022-04-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidee', '0003_guideeinfo_rvws_post_guideeinfo_rvws_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideeinfo',
            old_name='rvws_post',
            new_name='rvws_posted',
        ),
    ]
