# Generated by Django 4.0.3 on 2022-04-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_rating_status'),
        ('guidee', '0005_guideeinfo_ratings_given_guideeinfo_ratings_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideeinfo',
            name='ratings_given',
            field=models.ManyToManyField(blank=True, related_name='guidee_rated', to='entry.rating'),
        ),
        migrations.AlterField(
            model_name='guideeinfo',
            name='ratings_received',
            field=models.ManyToManyField(blank=True, related_name='guidee_received', to='entry.rating'),
        ),
    ]
