# Generated by Django 4.0.3 on 2022-06-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=500)),
                ('fd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.fields')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr1', to=settings.AUTH_USER_MODEL)),
                ('guidee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr2', to=settings.AUTH_USER_MODEL)),
                ('ques', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.question')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssg', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=4)),
                ('time_send', models.DateTimeField(auto_now_add=True)),
                ('time_received', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
